runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    script: app.app
    
  - url: /_ah/push-handlers/.*
    script: app.app
    login: admin

  - url: /_ah/push-handlers/.*
    script: app.app
    login: admin

libraries:
  - name: werkzeug
    version: 0.11.10

  - name: ssl
    version: latest

  - name: enum
    version: latest

  - name: jinja2
    version: latest

  - name: pytz
    version: latest

  - name: six
    version: latest
