runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:
- url: /.*
  script: main.app

libraries:
- name: werkzeug
  version: 0.11.10
  
- name: ssl
  version: latest
  
- name: enum
  version: latest
  
- name: jinja2
  version: latest
  
- name: pytz
  version: latest